name: go1.14+

on:
  workflow_dispatch:
  push:
  schedule:
    # Runs at 16:05 UTC on Sun (Every Monday at AM 01:05 JST, my time)
    - cron: '5 16 * * SUN'

jobs:
  go:
    name: Run tests on Go via container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run on Go 1.14
        run: docker-compose --file ./.github/docker-compose.yml up v1_14
      - name: Run on Go 1.15
        run: docker-compose --file ./.github/docker-compose.yml up v1_15
      - name: Run on Go 1.16
        run: docker-compose --file ./.github/docker-compose.yml up v1_16
      - name: Run on Go 1.17
        run: docker-compose --file ./.github/docker-compose.yml up v1_17
      - name: Run on latest Go
        run: docker-compose --file ./.github/docker-compose.yml up latest